apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: managed-cluster-1
  namespace: managed-cluster
spec:
  clusterName: managed-cluster-1
  clusterNamespace: managed-cluster
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: false
  iamPolicyController:
    enabled: false
  policyController:
    enabled: true
  searchCollector:
    enabled: false

# Note: This override replaces the entire KlusterletAddonConfig, and so must be
# provided in full. The templated portions will be substituted to match the
# cluster as defined in the SiteConfig, so it should be sufficient to adjust
# the 'enabled' flags to match the desired configuration
